// ========= Mock Data for UI/UX Prototype =========

export const mockModules = [
    {
        id: 1,
        moduleId: 101,
        title: 'Workplace Safety & Hazard Identification',
        quality: 'hq',
        sizeMB: 245,
        isCompleted: true,
        isDownloaded: true,
        lastAccessedAt: new Date('2026-02-18'),
        archivedAt: null,
        hqSizeBytes: 245 * 1024 * 1024,
        dsSizeBytes: 82 * 1024 * 1024,
    },
    {
        id: 2,
        moduleId: 102,
        title: 'Fire Safety & Emergency Evacuation Procedures',
        quality: 'ds',
        sizeMB: 78,
        isCompleted: true,
        isDownloaded: true,
        lastAccessedAt: new Date('2026-02-20'),
        archivedAt: null,
        hqSizeBytes: 198 * 1024 * 1024,
        dsSizeBytes: 78 * 1024 * 1024,
    },
    {
        id: 3,
        moduleId: 103,
        title: 'PPE Usage & Maintenance Standards',
        quality: 'hq',
        sizeMB: 312,
        isCompleted: false,
        isDownloaded: true,
        lastAccessedAt: new Date('2026-02-15'),
        archivedAt: null,
        hqSizeBytes: 312 * 1024 * 1024,
        dsSizeBytes: 105 * 1024 * 1024,
    },
    {
        id: 4,
        moduleId: 104,
        title: 'Chemical Handling & MSDS Documentation',
        quality: 'hq',
        sizeMB: 189,
        isCompleted: true,
        isDownloaded: true,
        lastAccessedAt: new Date('2026-01-10'),
        archivedAt: null,
        hqSizeBytes: 189 * 1024 * 1024,
        dsSizeBytes: 65 * 1024 * 1024,
    },
    {
        id: 5,
        moduleId: 105,
        title: 'Electrical Safety & Lockout/Tagout',
        quality: 'ds',
        sizeMB: 0,
        isCompleted: true,
        isDownloaded: false,
        lastAccessedAt: null,
        archivedAt: new Date('2026-01-28'),
        hqSizeBytes: 275 * 1024 * 1024,
        dsSizeBytes: 92 * 1024 * 1024,
    },
    {
        id: 6,
        moduleId: 106,
        title: 'Confined Space Entry Protocol',
        quality: 'hq',
        sizeMB: 0,
        isCompleted: false,
        isDownloaded: false,
        lastAccessedAt: null,
        archivedAt: new Date('2026-02-01'),
        hqSizeBytes: 340 * 1024 * 1024,
        dsSizeBytes: 115 * 1024 * 1024,
    },
    {
        id: 7,
        moduleId: 107,
        title: 'First Aid & CPR Certification',
        quality: 'hq',
        sizeMB: 156,
        isCompleted: false,
        isDownloaded: true,
        lastAccessedAt: new Date('2026-02-22'),
        archivedAt: null,
        hqSizeBytes: 156 * 1024 * 1024,
        dsSizeBytes: 52 * 1024 * 1024,
    },
    {
        id: 8,
        moduleId: 108,
        title: 'Working at Heights & Fall Protection',
        quality: 'ds',
        sizeMB: 67,
        isCompleted: false,
        isDownloaded: true,
        lastAccessedAt: new Date('2026-02-21'),
        archivedAt: null,
        hqSizeBytes: 210 * 1024 * 1024,
        dsSizeBytes: 67 * 1024 * 1024,
    },
];

export const mockResults = [
    {
        id: 'r1',
        moduleId: 101,
        moduleName: 'Workplace Safety & Hazard Identification',
        score: 42,
        maxScore: 50,
        percentageScore: 84,
        passed: true,
        completedAt: new Date('2026-02-18'),
        syncStatus: 'synced',
    },
    {
        id: 'r2',
        moduleId: 102,
        moduleName: 'Fire Safety & Emergency Evacuation',
        score: 38,
        maxScore: 50,
        percentageScore: 76,
        passed: true,
        completedAt: new Date('2026-02-15'),
        syncStatus: 'synced',
    },
    {
        id: 'r3',
        moduleId: 103,
        moduleName: 'PPE Usage & Maintenance Standards',
        score: 29,
        maxScore: 50,
        percentageScore: 58,
        passed: false,
        completedAt: new Date('2026-02-12'),
        syncStatus: 'local',
    },
    {
        id: 'r4',
        moduleId: 104,
        moduleName: 'Chemical Handling & MSDS Documentation',
        score: 47,
        maxScore: 50,
        percentageScore: 94,
        passed: true,
        completedAt: new Date('2026-02-08'),
        syncStatus: 'synced',
    },
    {
        id: 'r5',
        moduleId: 105,
        moduleName: 'Electrical Safety & Lockout/Tagout',
        score: 44,
        maxScore: 50,
        percentageScore: 88,
        passed: true,
        completedAt: new Date('2026-01-28'),
        syncStatus: 'synced',
    },
    {
        id: 'r6',
        moduleId: 107,
        moduleName: 'First Aid & CPR Certification',
        score: 22,
        maxScore: 50,
        percentageScore: 44,
        passed: false,
        completedAt: new Date('2026-02-20'),
        syncStatus: 'local',
    },
];

// ========= Detailed Assessment Breakdowns =========
export const mockAssessmentDetails = {
    'r1': {
        moduleName: 'Workplace Safety & Hazard Identification',
        timeSpent: '32:18',
        timeLimitMinutes: 45,
        attempts: 1,
        passingScore: 80,
        assessor: 'Auto-Graded System',
        submittedAt: new Date('2026-02-18T14:32:00'),
        topics: [
            { name: 'Hazard Identification', total: 12, correct: 11, percentage: 92 },
            { name: 'Risk Assessment', total: 10, correct: 8, percentage: 80 },
            { name: 'Safety Procedures', total: 15, correct: 13, percentage: 87 },
            { name: 'PPE Requirements', total: 8, correct: 7, percentage: 88 },
            { name: 'Incident Reporting', total: 5, correct: 3, percentage: 60 },
        ],
        questions: Array.from({ length: 50 }, (_, i) => ({
            num: i + 1,
            correct: [2, 8, 14, 22, 33, 39, 45, 48].indexOf(i) === -1,
        })),
        recommendation: 'Strengthen knowledge of Incident Reporting procedures. Review Chapter 4 on mandatory reporting timelines and escalation protocols.',
        certificate: true,
    },
    'r2': {
        moduleName: 'Fire Safety & Emergency Evacuation',
        timeSpent: '28:44',
        timeLimitMinutes: 45,
        attempts: 2,
        passingScore: 80,
        assessor: 'Auto-Graded System',
        submittedAt: new Date('2026-02-15T10:15:00'),
        topics: [
            { name: 'Fire Classes & Extinguishers', total: 10, correct: 7, percentage: 70 },
            { name: 'Evacuation Routes', total: 12, correct: 10, percentage: 83 },
            { name: 'Assembly Points', total: 8, correct: 7, percentage: 88 },
            { name: 'Fire Warden Duties', total: 10, correct: 8, percentage: 80 },
            { name: 'First Response', total: 10, correct: 6, percentage: 60 },
        ],
        questions: Array.from({ length: 50 }, (_, i) => ({
            num: i + 1,
            correct: [1, 5, 9, 11, 25, 31, 37, 40, 44, 47, 49].indexOf(i) === -1,
        })),
        recommendation: 'Review Fire Classes and First Response protocols. Chapter 2 covers extinguisher selection in detail — prioritise before next attempt.',
        certificate: false,
    },
    'r3': {
        moduleName: 'PPE Usage & Maintenance Standards',
        timeSpent: '41:05',
        timeLimitMinutes: 45,
        attempts: 1,
        passingScore: 80,
        assessor: 'Auto-Graded System',
        submittedAt: new Date('2026-02-12T09:00:00'),
        topics: [
            { name: 'PPE Selection', total: 10, correct: 5, percentage: 50 },
            { name: 'Donning & Doffing', total: 12, correct: 6, percentage: 50 },
            { name: 'Inspection Criteria', total: 10, correct: 7, percentage: 70 },
            { name: 'Storage Standards', total: 8, correct: 6, percentage: 75 },
            { name: 'Disposal Procedures', total: 10, correct: 5, percentage: 50 },
        ],
        questions: Array.from({ length: 50 }, (_, i) => ({
            num: i + 1,
            correct: [0,2,5,8,10,12,15,18,20,23,25,28,30,32,35,38,40,42,45,48].indexOf(i) === -1,
        })),
        recommendation: 'Significant gaps in PPE Selection and Donning/Doffing technique. Retake is required after completing Chapters 1–3. You scored 58% — passing mark is 80%.',
        certificate: false,
    },
    'r4': {
        moduleName: 'Chemical Handling & MSDS Documentation',
        timeSpent: '18:52',
        timeLimitMinutes: 45,
        attempts: 1,
        passingScore: 80,
        assessor: 'Auto-Graded System',
        submittedAt: new Date('2026-02-08T16:45:00'),
        topics: [
            { name: 'MSDS Reading', total: 12, correct: 12, percentage: 100 },
            { name: 'Hazard Labels', total: 10, correct: 9, percentage: 90 },
            { name: 'Safe Handling', total: 12, correct: 12, percentage: 100 },
            { name: 'Spill Response', total: 8, correct: 7, percentage: 88 },
            { name: 'Storage Compatibility', total: 8, correct: 7, percentage: 88 },
        ],
        questions: Array.from({ length: 50 }, (_, i) => ({
            num: i + 1,
            correct: [14, 29, 41].indexOf(i) === -1,
        })),
        recommendation: 'Excellent performance. Minor gaps in Spill Response containment priorities. Review Chapter 5 to achieve a perfect score on retake.',
        certificate: true,
    },
    'r5': {
        moduleName: 'Electrical Safety & Lockout/Tagout',
        timeSpent: '26:30',
        timeLimitMinutes: 45,
        attempts: 1,
        passingScore: 80,
        assessor: 'Auto-Graded System',
        submittedAt: new Date('2026-01-28T13:00:00'),
        topics: [
            { name: 'LOTO Procedures', total: 15, correct: 14, percentage: 93 },
            { name: 'Electrical Hazards', total: 10, correct: 9, percentage: 90 },
            { name: 'Arc Flash Safety', total: 10, correct: 9, percentage: 90 },
            { name: 'Inspection Protocols', total: 10, correct: 9, percentage: 90 },
            { name: 'Re-energisation Steps', total: 5, correct: 3, percentage: 60 },
        ],
        questions: Array.from({ length: 50 }, (_, i) => ({
            num: i + 1,
            correct: [7, 19, 35, 43, 48, 49].indexOf(i) === -1,
        })),
        recommendation: 'Strong overall result. Focus on the Re-energisation sequence — review the 8-step checklist in Chapter 6 to close the remaining gap.',
        certificate: true,
    },
    'r6': {
        moduleName: 'First Aid & CPR Certification',
        timeSpent: '43:55',
        timeLimitMinutes: 45,
        attempts: 1,
        passingScore: 80,
        assessor: 'Auto-Graded System',
        submittedAt: new Date('2026-02-20T11:10:00'),
        topics: [
            { name: 'CPR Technique', total: 12, correct: 4, percentage: 33 },
            { name: 'AED Operation', total: 8, correct: 3, percentage: 38 },
            { name: 'Wound Management', total: 10, correct: 7, percentage: 70 },
            { name: 'Shock Treatment', total: 10, correct: 5, percentage: 50 },
            { name: 'Scene Assessment', total: 10, correct: 3, percentage: 30 },
        ],
        questions: Array.from({ length: 50 }, (_, i) => ({
            num: i + 1,
            correct: [0,1,3,5,7,9,10,12,14,16,18,20,22,24,25,27,29,31,34,36,38,40,42,44,46,47,49].indexOf(i) === -1,
        })),
        recommendation: 'This result requires an immediate module retake. CPR Technique, AED Operation and Scene Assessment all scored below 40%. Attend the hands-on practical session before reattempting.',
        certificate: false,
    },
};

// ========= Module Extra Details =========
export const mockModuleDetails = {
    101: {
        instructor: { name: 'Sarah Mitchell', title: 'Senior HSE Compliance Officer', experience: '14 years' },
        duration: '3h 20m',
        lastUpdated: 'Jan 2026',
        prerequisites: ['Company Induction (Mandatory)'],
        learningOutcomes: [
            'Identify and classify workplace hazards across all risk categories',
            'Conduct a formal risk assessment using the company matrix',
            'Apply hierarchy of controls to eliminate or reduce risk',
            'Complete a workplace hazard register entry',
            'Report near-misses and incidents using the online portal',
        ],
        resources: [
            { name: 'Hazard Register Template (PDF)', size: '148 KB' },
            { name: 'Risk Assessment Matrix (PDF)', size: '92 KB' },
            { name: 'Module Reference Guide', size: '2.1 MB' },
        ],
        priorAttempts: [
            { date: new Date('2026-02-18'), score: 84, passed: true },
        ],
    },
    102: {
        instructor: { name: 'James Okafor', title: 'Fire Safety Consultant', experience: '11 years' },
        duration: '2h 50m',
        lastUpdated: 'Dec 2025',
        prerequisites: ['Workplace Safety & Hazard Identification (Module 101)'],
        learningOutcomes: [
            'Classify fire classes and select the correct extinguisher type',
            'Navigate primary and secondary evacuation routes',
            'Locate and communicate assembly point locations',
            'Carry out fire warden responsibilities during an evacuation',
            'Perform initial fire response without endangering others',
        ],
        resources: [
            { name: 'Site Evacuation Diagram (PDF)', size: '540 KB' },
            { name: 'Fire Extinguisher Quick Guide', size: '78 KB' },
            { name: 'Emergency Contacts Card', size: '34 KB' },
        ],
        priorAttempts: [
            { date: new Date('2026-02-10'), score: 72, passed: false },
            { date: new Date('2026-02-15'), score: 76, passed: true },
        ],
    },
    103: {
        instructor: { name: 'Priya Nair', title: 'Occupational Health Specialist', experience: '8 years' },
        duration: '4h 10m',
        lastUpdated: 'Feb 2026',
        prerequisites: ['Workplace Safety & Hazard Identification (Module 101)'],
        learningOutcomes: [
            'Select appropriate PPE for given hazard scenarios',
            'Correctly don and doff PPE for each equipment type',
            'Inspect PPE for defects before and after use',
            'Store and maintain equipment to manufacturer standards',
            'Safely dispose of contaminated or expired PPE',
        ],
        resources: [
            { name: 'PPE Selection Chart (PDF)', size: '215 KB' },
            { name: 'Inspection Checklist Template', size: '65 KB' },
            { name: 'Maintenance Log Sheet', size: '48 KB' },
            { name: 'SOP — Donning & Doffing (Video Guide)', size: '18.4 MB' },
        ],
        priorAttempts: [
            { date: new Date('2026-02-12'), score: 58, passed: false },
        ],
    },
    107: {
        instructor: { name: 'Tom Walsh', title: 'Certified First Aid Instructor', experience: '16 years' },
        duration: '2h 40m',
        lastUpdated: 'Nov 2025',
        prerequisites: ['Workplace Safety & Hazard Identification (Module 101)'],
        learningOutcomes: [
            'Assess an emergency scene for safety before responding',
            'Perform adult CPR to current resuscitation guidelines',
            'Operate an AED device through the full sequence',
            'Manage bleeding, burns and soft tissue wounds',
            'Recognise and treat clinical shock in a casualty',
        ],
        resources: [
            { name: 'First Aid Quick Reference Card', size: '112 KB' },
            { name: 'CPR Flow Chart (PDF)', size: '88 KB' },
            { name: 'AED Operation Walkthrough (PDF)', size: '310 KB' },
        ],
        priorAttempts: [
            { date: new Date('2026-02-20'), score: 44, passed: false },
        ],
    },
    108: {
        instructor: { name: 'David Chen', title: 'Height Safety Lead', experience: '12 years' },
        duration: '3h 50m',
        lastUpdated: 'Jan 2026',
        prerequisites: ['Workplace Safety & Hazard Identification (Module 101)', 'PPE Usage & Maintenance Standards (Module 103)'],
        learningOutcomes: [
            'Identify fall hazards during pre-task site assessments',
            'Select and fit fall arrest and restraint systems correctly',
            'Inspect harnesses, lanyards and anchor points',
            'Apply the hierarchy of controls to working at heights tasks',
            'Execute an emergency rescue plan for a fallen worker',
        ],
        resources: [
            { name: 'Heights Safety Plan Template', size: '188 KB' },
            { name: 'Harness Inspection Log', size: '55 KB' },
            { name: 'Rescue Procedure Flowchart', size: '140 KB' },
        ],
        priorAttempts: [],
    },
};

export const mockStorageStats = {
    totalUsedMB: 1047,
    deviceTotalGB: 64,
    deviceFreeMB: 18200,
    usagePercent: 32,
};

// Modules available for download (not yet downloaded)
export const availableModules = [
    {
        id: 9,
        moduleId: 109,
        title: 'Forklift Operation & Safety Training',
        hqSizeMB: 380,
        dsSizeMB: 128,
        duration: '4h 20m',
        category: 'Equipment',
    },
    {
        id: 10,
        moduleId: 110,
        title: 'Noise Exposure & Hearing Conservation',
        hqSizeMB: 195,
        dsSizeMB: 65,
        duration: '2h 45m',
        category: 'Health',
    },
    {
        id: 11,
        moduleId: 111,
        title: 'Crane & Rigging Safety Fundamentals',
        hqSizeMB: 420,
        dsSizeMB: 142,
        duration: '5h 10m',
        category: 'Equipment',
    },
    {
        id: 12,
        moduleId: 112,
        title: 'Scaffolding Safety & Inspection',
        hqSizeMB: 260,
        dsSizeMB: 88,
        duration: '3h 30m',
        category: 'Construction',
    },
];
